#!/bin/sh

source "./colors.sh"

# main bar & defaults
sketchybar  --bar   height=54       \
    margin=12       \
    y_offset=0      \
    padding_left=0  \
    padding_right=0 \
    color=0x00000000

sketchybar  --default   updates=when_shown                              \
    icon.font="Liga SFMono Nerd Font:Normal:16.0"   \
    icon.color=$FOREGROUND                          \
    label.font="Zed Mono:Bold:16.0" 		        \
    label.color=$FOREGROUND			                \
    label.y_offset=1 				                \
    y_offset=0
# set defaults
sketchybar  --default   background.color=$BACKGROUND        \
    blur_radius=2                       \
    background.corner_radius=15         \
    background.height=30                \
    background.border_color=$BLUE       \
    background.border_width=2

# ~~ left items ~~
source "./items/apple.sh"
source "./items/spaces.sh"
source "./items/media.sh"

# update defaults for right items
sketchybar  --default   background.padding_right=15 \
    icon.padding_left=12        \
    icon.padding_right=4        \
    label.padding_left=4        \
    label.padding_right=12      \

# ~~ right items ~~
source "./items/clock.sh"
source "./items/date.sh"
source "./items/weather.sh"
source "./items/battery.sh"

# finish config
sketchybar --hotload on
sketchybar --update
